config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :user_courses
  resources :courses
  namespace :supervisor do
    resources :users
    resources :subjects
    resources :tasks
    resources :courses
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password
  before_save { self.email = email.downcase }
  scope :supervisors, ->{where supervisor: "f"}
  scope :trainees, ->{where supervisor: false}
  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes :remember_digest, User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new digest.is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  private

  def downcase_email
    self.email= email.downcase
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < ApplicationController

  def index

  end

  def new
    @course = Course.new
    subjects = Subject.all
    subjects.each do |subject|
      @course.course_subjects.build subject: subject
    end
  end

  def create
    @course = Course.new course_params
    @course.user_id = current_user.id
    if @course.save
      redirect_to supervisor_courses_path
    else
      @subjects = Subject.all
      render "new"
    end
  end

  def show
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit :name,
      course_subjects_attributes: [:subject_id]
  end
end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @subjects = Subject.paginate page: params[:page], per_page: 10
  end

  def new
    @subject = Subject.new
    4.times{@subject.tasks.build}
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      redirect_to supervisor_subject_path @subject
    else
      render :new
    end
  end

  def show
    @subject = Subject.find params[:id]
    @tasks = @subject.tasks
  end

  def destroy
    @subject = Subject.find(params[:id]).destroy
    flash[:success]= t "deletedSubject"
    redirect_to supervisor_subjects_path
  end

  def edit
    @subject = Subject.find params[:id]
    @tasks = @subject.tasks
  end

  def update
    @subject = Subject.find params[:id]
    if @subject.update_attributes subject_params
      flash[:success] = t "subjectUpdated"
      redirect_to supervisor_subjects_path
    else
      render :edit
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, tasks_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end

  def index
    @trainees = User.trainees.paginate page: params[:page],
      per_page: 10
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @user= User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = t('SuccessUpdate')
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t('deletedUser')
    redirect_to supervisor_users_path
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t("signupSuccess")
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = t('SuccessUpdate')
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.supervisors.paginate page: params[:page], per_page: 6
  end

  def show
    @user= User.find params[:id]
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t "login2"
      redirect_to login_url
    end
  end

  private

  def user_params
   params.require(:user).permit :name, :email, :password,
     :password_confirmation
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/supervisor/users/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0
  col-sm-offset-0 col-md-offset-2 col-lg-offset-2">

    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t("userEditProfile") %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3 " align="center">
            <%= gravatar_for @user %>
          </div>
          <div class=" col-md-9 col-lg-9 ">
            <%= form_for @user, url: supervisor_user_path do |f| %>
              <%= render "layouts/messages", object: f.object %>
              <table class="table">
                  <tr>
                    <td><%= f.label :name %>:</td>
                    <td>
                      <%= f.text_field :name, class: "form-control" %>
                    </td>
                  </tr>
                  <tr>
                    <td><%= f.label :email %>:</td>
                    <td>
                      <%= f.email_field :email, class: "form-control" %>
                    </td>
                  </tr>
                  <tr>
                    <td><%= f.label :password %>:</td>
                    <td>
                      <%= f.password_field :password, class: "form-control" %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <%= f.label :password_confirmation, t("passConfirm") %>:
                    </td>
                    <td>
                      <%= f.password_field :password_confirmation,
                        class: "form-control" %>
                    </td>
                  </tr>
                  <tr>
                    <td><%= t "userSupervisorTag" %>:</td>
                    <td><b><%= @user.supervisor %></b ></td>
                  </tr>
                  <tr>
                    <td><%= t "userUpdateAtTag" %>:</td>
                    <td><%= l @user.updated_at, format: :define %></td>
                  </tr>
                  <tr>
                    <td colspan="2">
                      <%= f.submit t("saveUpdate"), class: "btn btn-primary" %>
                    </td>
                  </tr>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/supervisor/users/index.html.erb
<div class="container">
  <h1><%= t "traineeList" %></h1>
  <table class="table">
    <thead>
      <tr>
        <th><%= t "id" %></th>
        <th><%= t "userNameTag" %></th>
        <th><%= t "userEmailTag" %></th>
        <th><%= t "userCreatedAtTag" %></th>
        <th><%= t "editTrainee" %></th>
        <th><%= t "deleteTrainee" %></th>
      </tr>
    </thead>
    <tbody>
      <% @trainees.each do|trainee| %>
        <tr>
          <td><%= trainee.id %></td>
          <td><%= trainee.name %></td>
          <td><%= trainee.email %></td>
          <td><%= l trainee.created_at, format: :define %></td>
          <td><%= link_to t("editTrainee"), edit_supervisor_user_path(trainee.id) %></td>
          <td>
            <%= link_to t("deleteTrainee"), supervisor_user_path(trainee.id), method: :delete,
              data: {confirm: "Are you sure?"}, title: "Delete #{trainee.name}",
              class: 'text-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="center"><%= will_paginate @trainees %></div>
</div>

app/views/supervisor/users/new.html.erb
<% provide :title, t("titleSignup") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: supervisor_users_path do |f| %>
      <%= render "layouts/messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/supervisor/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0
  col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t "userProfile" %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3 " align="center">
            <%= gravatar_for @user %>
            <div><%= link_to t("editProfile") , edit_user_path %></div>
          </div>
          <div class=" col-md-9 col-lg-9 ">
            <table class="table">
                <tr>
                  <td><%= t "userNameTag" %>:</td>
                  <td><b><%= @user.name %></b></td>
                </tr>
                <tr>
                  <td><%= t "userEmailTag" %>:</td>
                  <td><b><%= @user.email %></b></td>
                </tr>
                <tr>
                  <td><%= t "userSupervisorTag" %>:</td>
                  <td><b><%= @user.supervisor %></b></td>
                </tr>
                <tr>
                  <td><%= t "userCreatedAtTag" %>:</td>
                  <td><%= @user.created_at.strftime("%A %d-%m-%Y") %></td>
                </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0
  col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t "activities" %></h3>
      </div>
      <div class="panel-body"></div>
    </div>
  </div>
</div>