config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :user_courses
  resources :courses
  namespace :supervisor do
    resources :users
    resources :subjects
    resources :tasks
    resources :courses
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  REJECT_NAME_BLANK_PROC = proc{|attributes| attributes["name"].blank?}
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks,
    reject_if: REJECT_NAME_BLANK_PROC, allow_destroy: true
  validates :name, presence: true
  has_many :course_subjects
  has_many :courses, through: :course_subjects
  has_many :user_subjects
  has_many :users, through: :user_subjects
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < ApplicationController

  def index

  end

  def new
    @course = Course.new
    subjects = Subject.all
    subjects.each do |subject|
      @course.course_subjects.build subject: subject
    end
  end

  def create
    @course = Course.new course_params
    @course.user_id = current_user.id
    if @course.save
      redirect_to supervisor_courses_path
    else
      @subjects = Subject.all
      render "new"
    end
  end

  def show
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit :name,
      course_subjects_attributes: [:subject_id]
  end
end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @subjects = Subject.paginate page: params[:page], per_page: 10
  end

  def new
    @subject = Subject.new
    4.times{@subject.tasks.build}
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      redirect_to supervisor_subject_path @subject
    else
      render :new
    end
  end

  def show
    @subject = Subject.find params[:id]
    @tasks = @subject.tasks
  end

  def destroy
    @subject = Subject.find(params[:id]).destroy
    flash[:success]= t "deletedSubject"
    redirect_to supervisor_subjects_path
  end

  def edit
    @subject = Subject.find params[:id]
    @tasks = @subject.tasks
  end

  def update
    @subject = Subject.find params[:id]
    if @subject.update_attributes subject_params
      flash[:success] = t "subjectUpdated"
      redirect_to supervisor_subjects_path
    else
      render :edit
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, tasks_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end

  def index
    @trainees = User.trainees.paginate page: params[:page],
      per_page: 10
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @user= User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = t('SuccessUpdate')
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t('deletedUser')
    redirect_to supervisor_users_path
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/views/supervisor/subjects/_form.html.erb
<%= form_for @subject, url: supervisor_subjects_path do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </p>
  <p>
   <button class="add_fields btn btn-primary" name="tasks"><%= t "addTask" %></button>
  </p>
  <p><%= f.submit t("createSubject"), class: "btn btn-primary" %></p>
  <%= new_fields_template f, :tasks %>
<% end %>

app/views/supervisor/subjects/_task_fields.html.erb
<div class="fields">
  <p>
    <%= f.hidden_field :_destroy %>
    <%= f.label :Task_name %>
    <button class="delete_fields btn btn-danger"><%= t "deleteTask" %></button>
    <%= f.text_field :name, class: "form-control" %>
  </p>
</div>

app/views/supervisor/subjects/edit.html.erb
<% provide :title, t("titleEditSubject") %>
<h1><%= t "updateSubject" %></h1>
<%= form_for [:supervisor, @subject] do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </p>
  <%= f.fields_for :tasks do |task| %>
    <%= render partial: "task_fields", locals: {f: task} %>
  <% end %>
  <p>
   <button class="add_fields btn btn-primary" name="tasks"><%= t "addTask" %></button>
  </p>
  <p><%= f.submit t("updateSubject"), class: "btn btn-primary" %></p>
  <%= new_fields_template f, :tasks %>
<% end %>

app/views/supervisor/subjects/index.html.erb
<% provide :title, t("titleAllSubject") %>

<h1><%= t "titleAllSubject" %></h1>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th><%= t "id" %></th>
      <th><%= t "subjectName" %></th>
      <th><%= t "subjectCratedAt" %></th>
      <th><%= t "editSubject" %></th>
      <th><%= t "deleteSubjet"%></th>
      <th><%= t "subjectDetail" %></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
        <td><%= subject.name %></td>
        <td><%= l subject.created_at, format: :define %></td>
        <td><%= link_to t("editSubject"), edit_supervisor_subject_path(subject) %></td>
        <td>
          <%= link_to t("deleteSubjet"), supervisor_subject_path(subject), method: :delete,
            data: {confirm: t("popupConfirm")}, title: "Delete #{subject.name}",
            class: "text-danger" %>
        </td>
        <td>
          <%= link_to t("subjectDetail"), supervisor_subject_path(subject), class: "text-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center"><%= will_paginate @subjects %></div>

app/views/supervisor/subjects/new.html.erb
<% provide :title, t("createSubject") %>
<h1>New Subject</h1>

<div class="row">
  <%= render partial: "form" %>
</div>

app/views/supervisor/subjects/show.html.erb
<% provide(:title, "Subject") %>

<div class="col-md-12">
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @subject.name %></h3>
      </div>
      <div class="panel-body">
        <p><%= @subject.description %></p>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= t("taskName") %></th>
                <th><%= t("taskDescription") %></th>
              </tr>
            </thead>
            <tbody>
              <% @tasks.each do |task| %>
                  <tr>
                    <td><%= task.name %></td>
                    <td><%= task.description %></td>
                  </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>