config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :user_courses
  resources :courses
  namespace :supervisor do
    resources :users
    resources :subjects
    resources :tasks
    resources :courses
  end
end

app/views/layouts/_admin_menu.html.erb
<li><%= link_to t("course"), courses_path %></li>
<li><%= link_to "Users", users_path %></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t "manageTrainee" %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t("showTrainee"), supervisor_users_path %></li>
    <li><%= link_to t("addTrainee"), new_supervisor_user_path  %></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t "manageSubject" %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to t("showAllSubject"), supervisor_subjects_path %>
    </li>
    <li>
      <%= link_to t("addNewSubject"), new_supervisor_subject_path %>
    </li>
  </ul>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t "manageCourse" %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to t("showCourse"), supervisor_courses_path %>
    </li>
    <li>
      <%= link_to t("addCourse"), new_supervisor_course_path  %>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t"Account"%> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("setting"), '#' %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("logout"), logout_path, method: "delete" %>
    </li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.facebook.com/">TMS_39</a>
    by <a href="https://www.google.com/">Huy Hoang</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.24h.com.vn/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "TSM_39 TRAINEE", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <% if logged_in? %>
          <% if is_supervisor? %>
            <%= render "layouts/admin_menu" %>
          <% else %>
            <%= render "layouts/trainee_menu" %>
          <% end %>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_trainee_menu.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t"Account"%> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("setting"), '#' %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("logout"), logout_path, method: "delete" %>
    </li>
  </ul>
 <li><%= link_to t("course"), courses_path %></li>
  <li><%= link_to t("memberofcourse"), user_courses_path %></li>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TSM_39 TRAINEE</title>
    <%= stylesheet_link_tag "application", media: "all",
     "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application",
     "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>